title: Hello, world! I'm Jimmy Sue
description: > # this means to ignore newlines until "baseurl:"
  鸡米酥的个人空间, 记录计算机视觉技术心得和最新动态.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jimmy Sue # add your name
author-img: avatar.jpg # add your photo
about-author: I am a computer vision engineer. Always hungry to keep learning. # add description
social-twitter: jimmysue0 # add your Twitter handle
social-github: jimmysue # add your Github handle
social-email: jimmysue.me@outlook.com # add your Email address

# Disqus
discus-identifier: jimmysue-github-io # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed
  - jekyll-archives

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]


navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags