"""Wrap a rendered MD body in the full per-post HTML shell.

Shell components (in order):
  <head>  — title, viewport, style.css, MathJax + highlight.js CDN, lightbox.js,
            TOC IntersectionObserver init script
  <body>
    <nav class="site-nav">  — injected by build.py from assets/nav-header.html
    <nav class="toc">       — generated by build_lib.headings, optional
    <main>                  — body_html
"""
from __future__ import annotations

import html as _html
from typing import Any


HEAD_TMPL = """<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{title}</title>
  <link rel="stylesheet" href="{prefix}assets/style.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/styles/atom-one-dark.min.css">
  <script>
    window.MathJax = {{ tex: {{ inlineMath: [['$','$'],['\\\\(','\\\\)']] }} }};
  </script>
  <script async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  <script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/highlight.min.js"></script>
  <script>document.addEventListener('DOMContentLoaded', () => hljs.highlightAll());</script>
  <script defer src="{prefix}assets/lightbox.js"></script>
  <script>
    document.addEventListener('DOMContentLoaded', () => {{
      const links = document.querySelectorAll('.toc a');
      if (!links.length) return;
      const map = new Map();
      links.forEach(a => {{
        const el = document.getElementById(a.getAttribute('href').slice(1));
        if (el) map.set(el, a);
      }});
      const observer = new IntersectionObserver((entries) => {{
        entries.forEach(e => {{
          const a = map.get(e.target);
          if (!a) return;
          if (e.isIntersecting) {{
            links.forEach(l => l.classList.remove('active'));
            a.classList.add('active');
            const toc = document.querySelector('.toc');
            if (toc) toc.scrollTo({{ top: a.offsetTop - toc.clientHeight / 2, behavior: 'smooth' }});
          }}
        }});
      }}, {{ rootMargin: '-20% 0px -70% 0px' }});
      map.forEach((_, el) => observer.observe(el));
    }});
  </script>
</head>
<body>
"""

TAIL = "</main>\n</body>\n</html>\n"


def assemble_post_page(
    meta: dict[str, Any],
    body_html: str,
    toc_html: str,
    nav_html: str,
    asset_prefix: str,
) -> str:
    """Compose the full per-post HTML page.

    asset_prefix: relative path from the post's own dir to repo root.
                  For papers/<slug>/index.html that's "../../".
    """
    title = _html.escape(str(meta.get("title", "Untitled")), quote=True)
    head = HEAD_TMPL.format(title=title, prefix=asset_prefix)
    parts = [head]
    if nav_html:
        parts.append(nav_html)
    if toc_html:
        parts.append(toc_html)
    parts.append("<main>\n")
    parts.append(body_html)
    parts.append(TAIL)
    return "".join(parts)
